# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 663d35a7f24c2de0a0ce598bc44216fac15b31bb5b97d435477380356f9da48085d058deccff2092b72438f641fa54adf890d018608aa961b32e1a6a34767915

test:
  secret_key_base: e48e1795fcc01966b00d98be493ace437cfe4db7152c31e611c9921bf5d49cd265a5ff4f8d6b34c7fcb05dba35480c707bd30bca724b8f5f3c2866f3208c3aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
